export interface DefaultPage {
  slug: string;
  title: string;
  content: string;
}

export const DEFAULT_PAGES: Record<string, DefaultPage> = {
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    content: `<h2>1. File Processing</h2>
<p>
  Files you upload are processed solely for the purpose of completing the requested PDF operation.
  They are stored temporarily in encrypted storage on our servers and are <strong>automatically and
  permanently deleted within 1 hour</strong> of upload. We do not read, analyse, index, or share
  your file contents.
</p>

<h2>2. No Account Required</h2>
<p>
  w3converter does not require registration. We do not collect your name, email address, or any
  personally identifiable information to use the free tools.
</p>

<h2>3. Analytics</h2>
<p>
  We use privacy-friendly analytics to measure aggregate usage (e.g., how many files were merged
  today). No individual user tracking or cross-site profiling is performed.
</p>

<h2>4. Cookies</h2>
<p>
  We use only essential cookies required for the service to function.
  We do not use tracking cookies without your explicit consent.
</p>

<h2>5. Advertising</h2>
<p>
  The free tier displays advertisements. Ad providers may set their own cookies in accordance with
  their own privacy policies. You may opt out via the cookie consent banner.
</p>

<h2>6. Data Retention</h2>
<p>
  Uploaded files and processed outputs are deleted within 1 hour. Server logs (IP address, user
  agent, tool used) are retained for up to 14 days for abuse prevention purposes.
</p>

<h2>7. Your Rights (GDPR / CCPA)</h2>
<p>
  You have the right to request deletion of any data we hold about you. Since files are deleted
  within 1 hour automatically, meaningful personal data is minimal. For log data inquiries,
  contact us at the email below.
</p>

<h2>8. Contact</h2>
<p>
  For privacy questions, contact us via the <a href="/contact">Contact page</a>.
</p>`
  },
  terms: {
    slug: "terms",
    title: "Terms of Service",
    content: `<h2>1. Acceptance</h2>
<p>
  By using w3converter (&ldquo;the Service&rdquo;), you agree to these Terms. If you do not agree, do not
  use the Service.
</p>

<h2>2. Permitted Use</h2>
<p>You may use the Service to process PDF files you own or have the legal right to modify. You may not:</p>
<ul>
  <li>Process files that contain illegal content or violate third-party intellectual property rights.</li>
  <li>Use the Service to circumvent copy protection in violation of applicable law.</li>
  <li>Automate bulk processing in a way that degrades service quality for other users.</li>
  <li>Attempt to reverse-engineer, hack, or disrupt the Service.</li>
</ul>

<h2>3. No Warranties</h2>
<p>
  The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee that
  converted files will be error-free or that the Service will be available at all times.
</p>

<h2>4. Limitation of Liability</h2>
<p>
  To the fullest extent permitted by law, w3converter shall not be liable for any indirect, incidental,
  or consequential damages arising from your use of the Service.
</p>

<h2>5. DMCA</h2>
<p>
  If you believe content processed through our Service infringes your copyright, contact us via the
  Contact page with details of the alleged infringement.
</p>

<h2>6. Changes</h2>
<p>
  We may update these Terms at any time. Continued use of the Service after changes constitutes
  acceptance.
</p>`
  },
  disclaimer: {
    slug: "disclaimer",
    title: "Disclaimer",
    content: `<h2>1. General Information</h2>
<p>
  The information provided by w3converter (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) on this website is for general informational purposes only. All information and tools on the Service are provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any tools or results.
</p>

<h2>2. No Professional Advice</h2>
<p>
  The Service does not contain legal, financial, or professional document advice. The file processing, converting, and editing utilities are automated tools. Any reliance on the output files or results generated by the Service is solely at your own risk. You should review and verify important documents before using them in official capacities.
</p>

<h2>3. Limitation of Liability</h2>
<p>
  Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service or reliance on any information or files processed through the Service. Your use of the Service and your reliance on any tools or information on the Service is solely at your own risk.
</p>

<h2>4. External Links</h2>
<p>
  The Service may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through our Service.
</p>`
  }
};
